
worker_processes auto;

events{

	#numeri di connessioni simultanee che un processo puo tenere
    worker_connections 1024;
}

http{
	include /etc/nginx/mime.types;
	server{

			listen 443 ssl;
			listen [::]:443 ssl;
			server_name localhost;

			# file certificato creato da openssl
			ssl_certificate /etc/nginx/certs/server.crt;
			# file chiave per decodificare il file certificato
			ssl_certificate_key /etc/nginx/certs/server.key;

			ssl_protocols TLSv1.2 TLSv1.3;
			#ssl_prefer_server_ciphers on;

			root /var/www/html;
			index index.php index.html;

			location / {
			try_files $uri $uri/ /index.html;
			}	


			error_log /var/log/nginx/error.log;
			access_log /var/log/nginx/access.log;
	}
}
