pipeline {
    agent { label 'agent1' }

    environment {
        IMAGE_NAME = 'welfare-backend'
        IMAGE_TAG   = "${env.GIT_COMMIT}"
    }
    stages {
        stage('showing git sha') {
            steps {
                echo "commit sha is ${env.GIT_COMMIT}"
            }
        }

        stage('running ls') {
            steps {
                sh "ls -last"
            }
        }
        stage("checking docker version") {
            steps {
                sh "docker --version"
            }
        }
        stage("Building backend image...") {
            steps {
                sh " docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ./backend"
            }
        }

        stage("Scan image with trivy") {
            steps {
                sh """
                  docker run --rm \
                    -v /var/run/docker.sock:/var/run/docker.sock \
                    -v /tmp/trivy-cache:/root/.cache/trivy \
                    aquasec/trivy:0.70.0 image \
                    --severity HIGH,CRITICAL \
                    --exit-code 1 \
                    ${IMAGE_NAME}:${IMAGE_TAG}
                  """
            }
        }
    }
}