pipeline {
    agent { label 'agent1' }

    stages {
        stage('showing git sha') {
            steps {
                echo "commit sha is ${env.GIT_COMMIT}"
            }
        }

        stage('running ll') {
            steps {
                sh "ll"
            }
        }
    }
}